import random

from prettytable import PrettyTable


def rules(chances):
    rule_table = PrettyTable()
    
    rule_table.add_column("When I say:", [])
    rule_table.add_column("That means", [])
    rule_table.add_row(["Pico", "One digit is correct but in the wrong position"])
    rule_table.add_row(["Fermi", "One digit is correct and in the right position"])
    rule_table.add_row(["Bagel", "No digit is correct"])

    print(rule_table)
    print(f"You have {chances} chances")

    return chances

def generating_number(num, num_list):

    for n in num:
        num_list.append(n)          # Creating list of number generated by computer
        
    return num_list

def verdict(num_list, guess_list, g1):
    c1 = guess_list[g1] == num_list[0]          # Comparing with 0th index of number of computer
    c2 = guess_list[g1] == num_list[1]          # Comparing with 1st index of number of computer 
    c3 = guess_list[g1] == num_list[2]          # Comparing with 2nd index of number of computer

    conditions = [c1, c2, c3]           # Creating a list of verdict of checking number

    '''
    If any one of the c1 c2 c3 are true then,
    it will check if the indexing is correct or not
    by comparing the g1 and conditions list then give Fermi verdict or Pico verdict.
    If the 1st if gets false immediately gives Bagel verdict
    '''

    if conditions[0] or conditions[1] or conditions[2]:
        if conditions[g1]:
            print("Fermi", end=' ')
        else:
            print("Pico", end=' ')
    else:
        print("Bagel", end=' ')

while True:
    print("\nI am thinking of a 3 digit number. Try to guess it")

    chances=10

    rules(chances)

    num = str(random.randint(100,999))              # Computer will generate 3 digit number randomly between 100 and 999
    num_list=[]

    generating_number(num, num_list)

    num_set=set(num_list)           # Creating a set of number generated by computer

    i=1
    while i<=10:           # As 10 chances is given, so loop will execute 10 times
        guess = input("\nWhat's your guess: ")          # Taking number from user
        guess_list=[]           # Creating a list of number of user

        for g in guess:
            guess_list.append(g)
        guess_set=set(guess_list)           # Creating a set of number of user

        for g1 in range(0, 3):
            verdict(num_list, guess_list, g1)         # Checking 1st, 2nd, 3rd number of user with all digit of number of computer
            
        if num_list == guess_list:           # If guess is correct
            print("\nYou win")
            break

        chances -= 1
        print(f"\n{chances} chances left")

        i += 1

        if(i==11):
            print("\nYou lose")
            print(f"My number is {num}")
    
    new = input("\nWant to guess more (YES or NO) : ").lower()

    if new == "no":
        exit()

